apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: dev
  labels:
    app: db
    project: infinity
spec:
  container:
    - name: mysql-container
      image: mysql:5.7
      env:
        - name: MYSQL_DATABASE
          value: accounts
        - name: MYSQL_ROOT_PASSWORD

