---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: vproapp
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer

