apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: dev
  labels:
    app: db
    project: infinity
spec:
  container:
    - name: mysql-container
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MY_ROOT_PASSWORD
